server:
  port: 80
#spring:
#  application:
#    name: microservice-constomer
eureka:
  instance:
    hostname: gaohwangh.com
      # 心跳时间，即服务续约间隔时间（缺省为30s）

    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

  client:
    registerWithEureka: false
    fetchRegistry: true  # 服务发现，false表示自己不从Eureka服务中获取注册信息
    serviceUrl: # Eureka客户端与Eureka服务端的交互地址，集群版配置对方的地址，单机版配置自己（如果不配置则默认本机8761端口）
#      defaultZone: http://gaohwang.com:6001/eureka/
      defaultZone: http://gaohwangh.com:6001/eureka/
#      defaultZone: http://localhost:6001/eureka/
#      ,http://eureka6002.com:6002/eureka/
#  instance:
#    instanceId: ${spring.application.name}:${server.port} # 指定实例ID,就不会显示主机名了
#    preferIpAddress: true #访问路径可以显示IP地址

    # 过期剔除时间，即服务续约到期时间（缺省为90s）
    registry-fetch-interval-seconds: 30

## 需要开启熔断
#feign:
#  hystrix:
#    enabled: true

feign-client:
  ourlove-server: ourlove-production

## 需要开启熔断
#feign:
#  hystrix:
#    enabled: true

#解决:com.netflix.client.ClientException: Load balancer does not have available server for client问题
ribbon:
  eureka:
    enabled: true