server:
  port: 8002
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml # mybatis配置文件所在路径
  type-aliases-package: com.gaohwangh.api.model # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml # mapper映射文件

spring:
  devtools:
    restart:
      enabled: false   #关闭热部署
  application:
     name: ourlove-production #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource # 当前数据源操作类型
      driver-class-name: com.mysql.jdbc.Driver # mysql驱动包
      url: jdbc:mysql://127.0.0.1:3306/ourlove?serverTimezone=GMT%2B8 # 数据
  #库名称
      username: root
      password: root
      dbcp2:
        min-idle: 5 # 数据库连接池的最小维持连接数
        initial-size: 5 # 初始化连接数
        max-total: 5 # 最大连接数
        max-wait-millis: 150 # 等待连接获取的最大超时时间
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true  # 服务发现，false表示自己不从Eureka服务中获取注册信息
    serviceUrl: # Eureka客户端与Eureka服务端的交互地址，集群版配置对方的地址，单机版配置自己（如果不配置则默认本机8761端口）
        defaultZone: http://gaohwangh.com:6001/eureka/
#      ,http://eureka6002.com:6002/eureka/
      # 设置拉取服务注册信息时间（缺省为60s）
    registry-fetch-interval-seconds: 30
  instance:
    instanceId: ${spring.application.name}:${server.port} # 指定实例ID,就不会显示主机名了
    preferIpAddress: true #访问路径可以显示IP地址
    # 显示IP地址
    # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-renewal-interval-in-seconds: 5
    # 过期剔除时间，即服务续约到期时间（缺省为90s）
    lease-expiration-duration-in-seconds: 10


##hystrix的超时时间
#hystrix:
#  command:
#    default:
#      execution:
#        timeout:
#          enabled: true
#        isolation:
#          thread:
#            timeoutInMilliseconds: 9000
##ribbon的超时时间
#ribbon:
#  ReadTimeout: 3000
#  ConnectTimeout: 3000
logging:
  level:
    root: info  #都采用info级别
    com.gaohwangh.production.dao: debug  #指定包名的位置使用DEBUG级别输出
  file: Logs/${spring.application.name}.log  #日志的输出位置
